#!/usr/bin/env bash
set -euo pipefail

# 5GPN optimized installer
# - Bootstraps Xiuyixx/5GPN
# - Applies the current proven policy:
#   direct-local -> proxy-local -> ChinaList -> default proxy
# - Keeps iOS profile/QR output
# - Updates remote AI rules daily
# - Disables UDP/443 QUIC path and suppresses proxy-domain AAAA/HTTPS/SVCB

BASE_DIR="/opt/proxy-gateway"
DNSDIST_DIR="/etc/dnsdist"
WWW_DIR="${BASE_DIR}/www"
IOS_PROFILE_PORT="${IOS_PROFILE_PORT:-8111}"
UPSTREAM_INSTALL_URL="${UPSTREAM_INSTALL_URL:-https://raw.githubusercontent.com/Xiuyixx/5GPN/main/install.sh}"
OPENAI_RULE_URL="${OPENAI_RULE_URL:-https://raw.githubusercontent.com/EAlyce/conf/main/Rule/OpenAI.list}"

DEFAULT_PRIVATE_OVERSEAS_DNS="${PRIVATE_OVERSEAS_DNS:-1.1.1.1 8.8.8.8 9.9.9.9}"
DEFAULT_PUBLIC_OVERSEAS_DNS="${PUBLIC_OVERSEAS_DNS:-1.1.1.1 8.8.8.8}"
DEFAULT_SNIPROXY_DNS="${SNIPROXY_DNS:-1.1.1.1 8.8.8.8 9.9.9.9}"

log() { printf '\033[0;34m[INFO]\033[0m %s\n' "$*"; }
ok() { printf '\033[0;32m[OK]\033[0m   %s\n' "$*"; }
warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*" >&2; }
err() { printf '\033[0;31m[ERR]\033[0m  %s\n' "$*" >&2; }

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    err "Run as root."
    exit 1
  fi
}

prompt_if_empty() {
  local var_name="$1" prompt="$2" default="${3:-}" value
  value="${!var_name:-}"
  if [[ -z "${value}" && -t 0 ]]; then
    if [[ -n "${default}" ]]; then
      read -r -p "${prompt} [${default}]: " value
      value="${value:-$default}"
    else
      read -r -p "${prompt}: " value
    fi
    printf -v "${var_name}" '%s' "${value}"
  fi
}

public_ip() {
  curl -4fsS --max-time 8 https://api.ipify.org 2>/dev/null ||
    curl -4fsS --max-time 8 https://ifconfig.me 2>/dev/null ||
    ip route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([0-9.]*\).*/\1/p' | head -n1
}

install_upstream_if_needed() {
  if [[ -x /usr/local/bin/update-dnsdist-rules.sh && -f "${DNSDIST_DIR}/dnsdist.conf.template" ]]; then
    log "Existing 5GPN installation detected; skipping upstream installer."
    return 0
  fi

  prompt_if_empty DOMAIN "Domain for DoT certificate (must already resolve to this server)"
  if [[ -z "${DOMAIN:-}" ]]; then
    err "DOMAIN is required for non-interactive optimized install."
    exit 1
  fi
  prompt_if_empty EMAIL "Let's Encrypt email" "admin@${DOMAIN}"

  log "Running upstream 5GPN installer. Domain: ${DOMAIN}"
  export DOMAIN EMAIL
  export PRIVATE_OVERSEAS_DNS="${PRIVATE_OVERSEAS_DNS:-$DEFAULT_PRIVATE_OVERSEAS_DNS}"
  export PUBLIC_OVERSEAS_DNS="${PUBLIC_OVERSEAS_DNS:-$DEFAULT_PUBLIC_OVERSEAS_DNS}"
  export SNIPROXY_DNS="${SNIPROXY_DNS:-$DEFAULT_SNIPROXY_DNS}"

  bash -c "$(curl -fsSL "${UPSTREAM_INSTALL_URL}")"
}

ensure_swap() {
  if swapon --show | grep -q .; then
    ok "Swap already enabled."
    return 0
  fi
  log "Enabling 1G swapfile."
  if command -v fallocate >/dev/null 2>&1; then
    fallocate -l 1G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=1024
  else
    dd if=/dev/zero of=/swapfile bs=1M count=1024
  fi
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '^/swapfile ' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
}

write_local_lists() {
  mkdir -p "${DNSDIST_DIR}"
  touch "${DNSDIST_DIR}/direct-local.txt" "${DNSDIST_DIR}/proxy-local.txt" "${DNSDIST_DIR}/block-local.txt"

  # Direct: explicit exclusions and iOS/Apple network probes that must not be proxied.
  cat > "${DNSDIST_DIR}/direct-local.txt.default" <<'EOF'
apple.com
apps.apple.com
captive.apple.com
cdn.jiedaibao.gs
configuration.apple.com
courier.push.apple.com
crl.apple.com
gsp-ssl.ls.apple.com
gspe1-ssl.ls.apple.com
hkcdn.longemby.com
icloud.com
init.itunes.apple.com
itunes.apple.com
itunes.apple.com.edgekey.net
jpcdn.longemby.com
mesu.apple.com
mm.iposl.com
mzstatic.com
ocsp.apple.com
ocsp2.apple.com
push.apple.com
swscan.apple.com
valid.apple.com
www.apple.com
www.icloud.com
xp.apple.com
EOF

  cat > "${DNSDIST_DIR}/proxy-local.txt.default" <<'EOF'
g.cn
google.cn
EOF

  # Merge defaults without destroying user additions.
  for name in direct-local proxy-local block-local; do
    if [[ -s "${DNSDIST_DIR}/${name}.txt.default" ]]; then
      cat "${DNSDIST_DIR}/${name}.txt" "${DNSDIST_DIR}/${name}.txt.default" 2>/dev/null |
        sed 's/#.*//; s/^[[:space:]]*//; s/[[:space:]]*$//; /^$/d' |
        sort -u > "${DNSDIST_DIR}/${name}.txt.tmp"
      mv "${DNSDIST_DIR}/${name}.txt.tmp" "${DNSDIST_DIR}/${name}.txt"
    fi
  done
  chmod 0644 "${DNSDIST_DIR}"/*-local.txt
}

write_dnsdist_template() {
  cat > "${DNSDIST_DIR}/dnsdist.conf.template" <<'EOF'
-- =============================================================================
-- dnsdist configuration for 5GPN optimized Smart DNS + DoT
-- Auto-generated by 5gpn-optimized-install.sh / update-dnsdist-rules.sh
-- =============================================================================

setServerPolicy(leastOutstanding)
addLocal("0.0.0.0:53", {doTCP=true})

certPath = "/etc/dnsdist/certs/fullchain.pem"
keyPath  = "/etc/dnsdist/certs/privkey.pem"
addTLSLocal("0.0.0.0:853", certPath, keyPath, {
    provider="openssl",
    sessionTickets=true,
    sessionTimeout=3600
})

newServer({address="127.0.0.1:5301", pool="china", name="china_dns_race", order=1, useClientSubnet=true})
__OVERSEAS_PRIVATE_DNS_SERVERS__
__OVERSEAS_PUBLIC_DNS_SERVERS__

setACL({"0.0.0.0/0", "::/0"})
privateClientRule = makeRule({"172.22.0.0/16"})
nonPrivateClientRule = NotRule(privateClientRule)

-- Keep classic DNS/53 restricted to 5GPN private clients; public clients use DoT/853.
addAction(AndRule({nonPrivateClientRule, DSTPortRule(53)}), DropAction())
addAction(MaxQPSIPRule(10000), DropAction())

-- =============================================================================
-- Domain Lists
-- =============================================================================

local blockList = newSuffixMatchNode()
__BLOCKLIST_RULES__

local directList = newSuffixMatchNode()
__DIRECTLIST_RULES__

local proxyList = newSuffixMatchNode()
__PROXYLIST_RULES__

-- Generated for reference/compatibility. In default-proxy mode, routing does
-- not depend on GFWList, but the list remains available for future policies.
local gfwList = newSuffixMatchNode()
__GFWLIST_RULES__

local chinaList = newSuffixMatchNode()
__CHINALIST_RULES__

-- =============================================================================
-- Routing Logic
-- =============================================================================

local serverIP = "__SERVER_IP__"
local chinaECS = "139.226.48.0/24"
local neutralECSv4 = "0.0.0.0/0"
local neutralECSv6 = "::/0"

-- 1. Explicit block: empty answer.
addAction(LuaRule(function(dq) return blockList:check(dq.qname) end), RCodeAction(DNSRCode.NOERROR))

-- 2. Explicit direct. Preserve HTTPS/SVCB for iOS/Apple and direct domains.
addAction(AndRule({privateClientRule, LuaRule(function(dq) return directList:check(dq.qname) end)}), SetECSOverrideAction(true))
addAction(AndRule({privateClientRule, LuaRule(function(dq) return directList:check(dq.qname) end)}), SetECSAction(neutralECSv4, neutralECSv6))
addAction(AndRule({privateClientRule, LuaRule(function(dq) return directList:check(dq.qname) end)}), PoolAction("overseas_private"))
addAction(AndRule({nonPrivateClientRule, LuaRule(function(dq) return directList:check(dq.qname) end)}), SetECSOverrideAction(true))
addAction(AndRule({nonPrivateClientRule, LuaRule(function(dq) return directList:check(dq.qname) end)}), SetECSAction(neutralECSv4, neutralECSv6))
addAction(AndRule({nonPrivateClientRule, LuaRule(function(dq) return directList:check(dq.qname) end)}), PoolAction("overseas_public"))

-- 3. Force proxy before ChinaList, and suppress records that can bypass A spoofing.
addAction(AndRule({LuaRule(function(dq) return proxyList:check(dq.qname) end), QTypeRule(DNSQType.A)}), SpoofAction(serverIP))
addAction(AndRule({LuaRule(function(dq) return proxyList:check(dq.qname) end), QTypeRule(DNSQType.AAAA)}), RCodeAction(DNSRCode.NOERROR))
addAction(AndRule({LuaRule(function(dq) return proxyList:check(dq.qname) end), QTypeRule(DNSQType.HTTPS)}), RCodeAction(DNSRCode.NOERROR))
addAction(AndRule({LuaRule(function(dq) return proxyList:check(dq.qname) end), QTypeRule(DNSQType.SVCB)}), RCodeAction(DNSRCode.NOERROR))

-- 4. ChinaList direct. Preserve HTTPS/SVCB for domestic/direct sites.
addAction(LuaRule(function(dq) return chinaList:check(dq.qname) end), SetECSOverrideAction(true))
addAction(LuaRule(function(dq) return chinaList:check(dq.qname) end), SetECSAction(chinaECS))
addAction(LuaRule(function(dq) return chinaList:check(dq.qname) end), PoolAction("china"))

-- 5. Default proxy: all remaining A records point to the control node.
addAction(QTypeRule(DNSQType.A), SpoofAction(serverIP))

-- 6. Proxy guardrails for everything not direct/ChinaList.
addAction(QTypeRule(DNSQType.AAAA), RCodeAction(DNSRCode.NOERROR))
addAction(QTypeRule(DNSQType.HTTPS), RCodeAction(DNSRCode.NOERROR))
addAction(QTypeRule(DNSQType.SVCB), RCodeAction(DNSRCode.NOERROR))

-- 7. Other qtypes route normally by source network.
addAction(AndRule({privateClientRule, AllRule()}), SetECSOverrideAction(true))
addAction(AndRule({privateClientRule, AllRule()}), SetECSAction(neutralECSv4, neutralECSv6))
addAction(AndRule({privateClientRule, AllRule()}), PoolAction("overseas_private"))
addAction(AndRule({nonPrivateClientRule, AllRule()}), SetECSOverrideAction(true))
addAction(AndRule({nonPrivateClientRule, AllRule()}), SetECSAction(neutralECSv4, neutralECSv6))
addAction(AndRule({nonPrivateClientRule, AllRule()}), PoolAction("overseas_public"))

-- =============================================================================
-- Cache
-- =============================================================================

local chinaCache = newPacketCache(500000, {
    maxTTL=86400,
    minTTL=300,
    temporaryFailureTTL=60,
    staleTTL=300
})
local privateOverseasCache = newPacketCache(500000, {
    maxTTL=86400,
    minTTL=300,
    temporaryFailureTTL=60,
    staleTTL=300
})
local publicOverseasCache = newPacketCache(500000, {
    maxTTL=86400,
    minTTL=300,
    temporaryFailureTTL=60,
    staleTTL=300
})
getPool("china"):setCache(chinaCache)
getPool("overseas_private"):setCache(privateOverseasCache)
getPool("overseas_public"):setCache(publicOverseasCache)
EOF
}

write_update_script() {
  cat > /usr/local/bin/update-dnsdist-rules.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="/etc/dnsdist"
GFWLIST_URL="https://github.com/gfwlist/gfwlist/raw/master/gfwlist.txt"
CHINALIST_URL="https://github.com/felixonmars/dnsmasq-china-list/raw/master/accelerated-domains.china.conf"
OPENAI_RULE_URL="${OPENAI_RULE_URL:-https://raw.githubusercontent.com/EAlyce/conf/main/Rule/OpenAI.list}"
GFWLIST_FILE="${BASE_DIR}/gfwlist.raw"
CHINALIST_FILE="${BASE_DIR}/chinalist.raw"
GFWLIST_LUA="${BASE_DIR}/gfwlist.lua"
CHINALIST_LUA="${BASE_DIR}/chinalist.lua"
CHINALIST_CHUNK_DIR="${BASE_DIR}/chinalist.d"
CHINALIST_CHUNK_SIZE=20000
GFWLIST_EXTRA_FILE="${BASE_DIR}/gfwlist-extra-local.txt"
OPENAI_RULE_FILE="${BASE_DIR}/gfwlist-extra-openai-remote.txt"
DIRECTLIST_FILE="${BASE_DIR}/direct-local.txt"
PROXYLIST_FILE="${BASE_DIR}/proxy-local.txt"
BLOCKLIST_FILE="${BASE_DIR}/block-local.txt"
DNSDIST_TEMPLATE="${BASE_DIR}/dnsdist.conf.template"
DNSDIST_CONF="${BASE_DIR}/dnsdist.conf"
DEFAULT_OVERSEAS_DNS=("1.1.1.1" "8.8.8.8" "9.9.9.9")
DEFAULT_PUBLIC_OVERSEAS_DNS=("1.1.1.1" "8.8.8.8")

render_overseas_dns_servers() {
  local input="${1:-}" pool="${2:-overseas}" prefix="${3:-overseas}"
  local dns_list=() item order=1 name
  if [[ -z "$input" ]]; then dns_list=("${DEFAULT_OVERSEAS_DNS[@]}"); else input="${input//,/ }"; read -r -a dns_list <<< "$input"; fi
  for item in "${dns_list[@]}"; do
    [[ -z "$item" ]] && continue
    [[ "$item" =~ ^[0-9A-Fa-f:.]+$ ]] || { echo "[!] Skipping invalid DNS address: $item" >&2; continue; }
    name="${prefix}${order}"
    printf 'newServer({address="%s:53", pool="%s", name="%s", order=%d, useClientSubnet=true})\n' "$item" "$pool" "$name" "$order"
    order=$((order + 1))
  done
}

clean_domain_stream() {
  sed 's/\r$//' |
    sed 's/#.*//; s/^[[:space:]]*//; s/[[:space:]]*$//; s/^\*\.//; s/^\.//; s/\.$//; /^$/d' |
    awk '{print tolower($0)}' |
    awk 'BEGIN{ok="^([a-z0-9]([a-z0-9_-]*[a-z0-9])?\\.)+[a-z0-9]([a-z0-9_-]*[a-z0-9])?$"} $0 ~ ok {print}' |
    sort -u
}

render_suffix_list_rules() {
  local list_name="$1" list_file="$2" count=0 domain
  [[ -f "$list_file" ]] || return 0
  while IFS= read -r domain || [[ -n "$domain" ]]; do
    [[ -z "$domain" ]] && continue
    printf '%s:add(newDNSName("%s"))\n' "$list_name" "$domain"
    count=$((count + 1))
  done < <(clean_domain_stream < "$list_file")
  echo "[+] $(basename "$list_file"): ${count} domains" >&2
}

append_gfwlist_extras() {
  touch "$GFWLIST_LUA"
  local idx="${BASE_DIR}/gfwlist.domains" domain extra_file count=0
  sed -n 's/^gfwList:add(newDNSName("\(.*\)"))$/\1/p' "$GFWLIST_LUA" | sort -u > "$idx"
  for extra_file in "$GFWLIST_EXTRA_FILE" "$OPENAI_RULE_FILE"; do
    [[ -f "$extra_file" ]] || continue
    while IFS= read -r domain; do
      grep -Fxq "$domain" "$idx" && continue
      echo "gfwList:add(newDNSName(\"${domain}\"))" >> "$GFWLIST_LUA"
      echo "$domain" >> "$idx"
      count=$((count + 1))
    done < <(clean_domain_stream < "$extra_file")
  done
  rm -f "$idx"
  echo "[+] GFWList extras: ${count} domains"
}

sync_openai_remote_rules() {
  local tmp_file tmp_domains
  tmp_file=$(mktemp "${BASE_DIR}/openai.list.tmp.XXXXXX")
  tmp_domains=$(mktemp "${BASE_DIR}/openai.domains.tmp.XXXXXX")
  if wget -qO "$tmp_file" "$OPENAI_RULE_URL" 2>/dev/null || curl -fsSL "$OPENAI_RULE_URL" -o "$tmp_file" 2>/dev/null; then
    awk -F, '/^DOMAIN,/ {print $2} /^DOMAIN-SUFFIX,/ {print $2}' "$tmp_file" | clean_domain_stream > "$tmp_domains"
    mv "$tmp_domains" "$OPENAI_RULE_FILE"
    chmod 0644 "$OPENAI_RULE_FILE"
    echo "[+] OpenAI remote rules synced: $(wc -l < "$OPENAI_RULE_FILE") domains"
  else
    echo "[!] Failed to download OpenAI remote rules; using cached copy if present" >&2
    rm -f "$tmp_domains"
  fi
  rm -f "$tmp_file"
}

write_chinalist_chunks() {
  local tmp_chunk_dir="$1" tmp_loader="$2"
  local count=0 chunk_index=0 entries=0 chunk_file="" basename final_path
  local chunk_paths=()
  mkdir -p "$tmp_chunk_dir"
  start_chunk() {
    printf -v basename 'chinalist-%03d.lua' "$chunk_index"
    chunk_file="${tmp_chunk_dir}/${basename}"
    final_path="${CHINALIST_CHUNK_DIR}/${basename}"
    printf 'local chinaList = ...\n' > "$chunk_file"
    chunk_paths+=("$final_path")
    chunk_index=$((chunk_index + 1))
    entries=0
  }
  while IFS= read -r domain; do
    [[ -z "$domain" ]] && continue
    [[ $entries -eq 0 ]] && start_chunk
    echo "chinaList:add(newDNSName(\"${domain}\"))" >> "$chunk_file"
    count=$((count + 1)); entries=$((entries + 1))
    [[ $entries -ge $CHINALIST_CHUNK_SIZE ]] && entries=0
  done < <(grep -oP 'server=/\K[^/]+' "$CHINALIST_FILE" | clean_domain_stream)
  if [[ ${#chunk_paths[@]} -eq 0 ]]; then
    echo "-- (no chinalist rules loaded)" > "$tmp_loader"
  else
    {
      echo "local chinalistChunks = {"
      for final_path in "${chunk_paths[@]}"; do printf '    "%s",\n' "$final_path"; done
      echo "}"
      echo "for _, chunk in ipairs(chinalistChunks) do"
      echo "    assert(loadfile(chunk))(chinaList)"
      echo "end"
    } > "$tmp_loader"
  fi
  chmod -R u=rwX,go=rX "$tmp_chunk_dir"
  chmod 0644 "$tmp_loader"
  echo "$count"
}

install_chinalist_chunks() {
  local tmp_chunk_dir="$1" tmp_loader="$2" old="${CHINALIST_CHUNK_DIR}.old"
  rm -rf "$old"
  [[ -d "$CHINALIST_CHUNK_DIR" ]] && mv "$CHINALIST_CHUNK_DIR" "$old"
  mv "$tmp_chunk_dir" "$CHINALIST_CHUNK_DIR"
  mv "$tmp_loader" "$CHINALIST_LUA"
  rm -rf "$old"
}

echo "[$(date)] Starting 5GPN rule update..."
mkdir -p "$BASE_DIR"
sync_openai_remote_rules

echo "[*] Downloading GFWList..."
if wget -qO "$GFWLIST_FILE" "$GFWLIST_URL" 2>/dev/null || curl -fsSL "$GFWLIST_URL" -o "$GFWLIST_FILE" 2>/dev/null; then
  decoded="${BASE_DIR}/gfwlist.decoded"
  > "$decoded"
  base64 -d "$GFWLIST_FILE" > "$decoded" 2>/dev/null ||
    base64 -d -i "$GFWLIST_FILE" > "$decoded" 2>/dev/null ||
    openssl enc -base64 -d -in "$GFWLIST_FILE" > "$decoded" 2>/dev/null || true
  > "$GFWLIST_LUA"
  count=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*[![\]].* || -z "$line" ]] && continue
    domain=""
    if [[ "$line" =~ ^\|\|(.+)\^*$ ]]; then domain="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ ^\|https?://([^/]+) ]]; then domain="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ ^\*\.(.+) ]]; then domain="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ ^[a-zA-Z0-9]([a-zA-Z0-9.-]+) ]]; then domain="$line"; fi
    domain=$(printf '%s\n' "$domain" | clean_domain_stream || true)
    [[ -z "$domain" ]] && continue
    echo "gfwList:add(newDNSName(\"${domain}\"))" >> "$GFWLIST_LUA"
    count=$((count + 1))
    [[ $count -ge 20000 ]] && break
  done < "$decoded"
  rm -f "$decoded"
  echo "[+] GFWList: ${count} domains"
else
  echo "[!] Failed to download GFWList" >&2
  touch "$GFWLIST_LUA"
fi
append_gfwlist_extras

echo "[*] Downloading ChinaList..."
if wget -qO "$CHINALIST_FILE" "$CHINALIST_URL" 2>/dev/null || curl -fsSL "$CHINALIST_URL" -o "$CHINALIST_FILE" 2>/dev/null; then
  tmp_chunk_dir=$(mktemp -d "${BASE_DIR}/chinalist.d.tmp.XXXXXX")
  tmp_loader=$(mktemp "${BASE_DIR}/chinalist.lua.tmp.XXXXXX")
  count=$(write_chinalist_chunks "$tmp_chunk_dir" "$tmp_loader")
  install_chinalist_chunks "$tmp_chunk_dir" "$tmp_loader"
  echo "[+] ChinaList: ${count} domains"
else
  echo "[!] Failed to download ChinaList" >&2
  touch "$CHINALIST_LUA"
fi

SERVER_IP=$(cat "${BASE_DIR}/.public_ip" 2>/dev/null || ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[\d.]+' || echo "127.0.0.1")
DOMAIN=$(cat "${BASE_DIR}/.domain" 2>/dev/null || echo "example.com")
CERT_BASENAME="$DOMAIN"
[[ -f /opt/proxy-gateway/etc/.cert_basename ]] && CERT_BASENAME=$(cat /opt/proxy-gateway/etc/.cert_basename)
PRIVATE_OVERSEAS_DNS=$(cat "${BASE_DIR}/.overseas_private_dns" 2>/dev/null || cat "${BASE_DIR}/.overseas_dns" 2>/dev/null || echo "${DEFAULT_OVERSEAS_DNS[*]}")
PUBLIC_OVERSEAS_DNS=$(cat "${BASE_DIR}/.overseas_public_dns" 2>/dev/null || echo "${DEFAULT_PUBLIC_OVERSEAS_DNS[*]}")

OVERSEAS_PRIVATE_DNS_SERVERS=$(render_overseas_dns_servers "$PRIVATE_OVERSEAS_DNS" "overseas_private" "overseas_private")
OVERSEAS_PUBLIC_DNS_SERVERS=$(render_overseas_dns_servers "$PUBLIC_OVERSEAS_DNS" "overseas_public" "overseas_public")
DIRECTLIST_RULES=$(render_suffix_list_rules directList "$DIRECTLIST_FILE")
PROXYLIST_RULES=$(render_suffix_list_rules proxyList "$PROXYLIST_FILE")
BLOCKLIST_RULES=$(render_suffix_list_rules blockList "$BLOCKLIST_FILE")

python3 - "$DNSDIST_TEMPLATE" "$GFWLIST_LUA" "$CHINALIST_LUA" "$SERVER_IP" "$CERT_BASENAME" "$OVERSEAS_PRIVATE_DNS_SERVERS" "$OVERSEAS_PUBLIC_DNS_SERVERS" "$DNSDIST_CONF" "$DIRECTLIST_RULES" "$PROXYLIST_RULES" "$BLOCKLIST_RULES" <<'PYEOF'
import sys
template_path, gfw_path, china_path, server_ip, domain, overseas_private_servers, overseas_public_servers, output_path, direct_rules, proxy_rules, block_rules = sys.argv[1:12]
with open(template_path, "r", encoding="utf-8") as f:
    content = f.read()
with open(gfw_path, "r", encoding="utf-8") as f:
    gfw_rules = f.read().strip() or "-- (no gfwlist rules loaded)"
with open(china_path, "r", encoding="utf-8") as f:
    china_rules = f.read().strip() or "-- (no chinalist rules loaded)"
replacements = {
    "__GFWLIST_RULES__": gfw_rules,
    "__CHINALIST_RULES__": china_rules,
    "__DIRECTLIST_RULES__": direct_rules.strip() or "-- (no direct rules loaded)",
    "__PROXYLIST_RULES__": proxy_rules.strip() or "-- (no force-proxy rules loaded)",
    "__BLOCKLIST_RULES__": block_rules.strip() or "-- (no block rules loaded)",
    "__SERVER_IP__": server_ip,
    "__DOMAIN__": domain,
    "__OVERSEAS_PRIVATE_DNS_SERVERS__": overseas_private_servers,
    "__OVERSEAS_PUBLIC_DNS_SERVERS__": overseas_public_servers,
}
for k, v in replacements.items():
    content = content.replace(k, v)
with open(output_path, "w", encoding="utf-8") as f:
    f.write(content)
PYEOF

echo "[OK]   dnsdist configuration generated"
dnsdist --check-config -C "$DNSDIST_CONF"
echo "[OK]   dnsdist configuration validated"
if systemctl is-active --quiet dnsdist; then
  systemctl reload dnsdist 2>/dev/null || systemctl restart dnsdist
  sleep 1
  systemctl is-active --quiet dnsdist || systemctl restart dnsdist
else
  systemctl start dnsdist
fi
echo "[$(date)] 5GPN rule update completed."
EOF
  chmod +x /usr/local/bin/update-dnsdist-rules.sh
}

configure_firewall_and_services() {
  log "Configuring firewall and service reliability."
  if command -v nft >/dev/null 2>&1; then
    cp -a /etc/nftables.conf "/etc/nftables.conf.bak.5gpn.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
    cat > /etc/nftables.conf <<'EOF'
#!/usr/sbin/nft -f
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif "lo" accept
        ct state established,related accept
        tcp dport { 22, 53, 443, 853, 8111 } accept
        udp dport 53 accept
        udp dport 443 reject
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
    }
    chain forward {
        type filter hook forward priority 0; policy accept;
    }
    chain output {
        type filter hook output priority 0; policy accept;
    }
}
EOF
    nft -f /etc/nftables.conf
    systemctl enable nftables >/dev/null 2>&1 || true
  else
    warn "nft not found; please manually reject UDP/443 and allow TCP/443."
  fi

  systemctl stop quic-proxy 2>/dev/null || true
  systemctl disable quic-proxy >/dev/null 2>&1 || true

  # Upstream 5GPN units commonly use /usr/local/sbin/sniproxy. Some distros'
  # packages install sniproxy at /usr/sbin/sniproxy instead, causing
  # status=203/EXEC. Keep the unit stable by normalizing the expected path.
  if [[ ! -x /usr/local/sbin/sniproxy && -x /usr/sbin/sniproxy ]]; then
    mkdir -p /usr/local/sbin
    ln -s /usr/sbin/sniproxy /usr/local/sbin/sniproxy
  fi

  mkdir -p /etc/systemd/system/sniproxy.service.d
  cat > /etc/systemd/system/sniproxy.service.d/reliability.conf <<'EOF'
[Service]
Restart=always
RestartSec=2
EOF
  systemctl daemon-reload
  systemctl restart sniproxy 2>/dev/null || true
}

configure_rule_timer() {
  cat > /etc/systemd/system/update-dnsdist-rules.service <<'EOF'
[Unit]
Description=Update dnsdist 5GPN rules

[Service]
Type=oneshot
ExecStart=/usr/local/bin/update-dnsdist-rules.sh
EOF
  cat > /etc/systemd/system/update-dnsdist-rules.timer <<'EOF'
[Unit]
Description=Daily dnsdist 5GPN rule update

[Timer]
OnCalendar=*-*-* 03:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
  systemctl daemon-reload
  systemctl enable --now update-dnsdist-rules.timer
}

write_healthcheck() {
  cat > /usr/local/bin/5gpn-healthcheck.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
SERVER_IP=$(cat /etc/dnsdist/.public_ip 2>/dev/null || ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[\d.]+' || echo 127.0.0.1)
DOT_NAME=$(cat /etc/dnsdist/.domain 2>/dev/null || echo localhost)
fail=0

check_service() {
  local svc="$1"
  if systemctl is-active --quiet "$svc"; then echo "OK service $svc"; else echo "FAIL service $svc"; fail=1; fi
}

check_dot() {
  python3 - "$SERVER_IP" "$DOT_NAME" <<'PY' || return 1
import socket, ssl, struct, random, sys
server, sni = sys.argv[1], sys.argv[2]
checks = [("chatgpt.com",1,server),("auth.openai.com",1,server),("chatgpt.com",65,None),("auth.openai.com",65,None),("baidu.com",1,"not-proxy"),("captive.apple.com",1,"not-proxy")]
def enc(name):
    out=b""
    for p in name.split("."): out += bytes([len(p)]) + p.encode()
    return out+b"\0"
def skip(data, off):
    while True:
        l=data[off]
        if l & 0xc0: return off+2
        if l == 0: return off+1
        off += 1+l
def query(name, qtype):
    pkt=struct.pack("!HHHHHH", random.randrange(65536),0x0100,1,0,0,0)+enc(name)+struct.pack("!HH",qtype,1)
    ctx=ssl._create_unverified_context(); raw=socket.create_connection((server,853),timeout=5); s=ctx.wrap_socket(raw,server_hostname=sni)
    s.sendall(struct.pack("!H",len(pkt))+pkt); hdr=s.recv(2); n=struct.unpack("!H",hdr)[0]
    data=b""
    while len(data)<n: data += s.recv(n-len(data))
    s.close(); an=struct.unpack("!H",data[6:8])[0]; off=12
    for _ in range(struct.unpack("!H",data[4:6])[0]): off=skip(data,off)+4
    ips=[]
    for _ in range(an):
        off=skip(data,off); typ,cls,ttl,rdlen=struct.unpack("!HHIH",data[off:off+10]); off+=10
        rdata=data[off:off+rdlen]; off+=rdlen
        if typ==1 and rdlen==4: ips.append(socket.inet_ntoa(rdata))
    return an, ips
bad=False
for name,qtype,expect in checks:
    an,ips=query(name,qtype)
    ok = (an == 0) if expect is None else ((server not in ips and an > 0) if expect == "not-proxy" else expect in ips)
    print(("OK" if ok else "FAIL"), "dot", name, qtype, ips, "answers", an)
    bad = bad or not ok
raise SystemExit(1 if bad else 0)
PY
}

check_tcp_sni() {
  if timeout 8 openssl s_client -connect "${SERVER_IP}:443" -servername chatgpt.com -brief </dev/null 2>&1 | grep -q 'Peer certificate: CN=chatgpt.com'; then
    echo "OK tcp443 chatgpt.com"
  else
    echo "FAIL tcp443 chatgpt.com"
    fail=1
  fi
}

check_service dnsdist
check_service sniproxy
check_dot || fail=1
check_tcp_sni
free -h | sed 's/^/MEM /'
exit "$fail"
EOF
  chmod +x /usr/local/bin/5gpn-healthcheck.sh
  cat > /etc/systemd/system/5gpn-healthcheck.service <<'EOF'
[Unit]
Description=5GPN healthcheck

[Service]
Type=oneshot
ExecStart=/usr/local/bin/5gpn-healthcheck.sh
EOF
  cat > /etc/systemd/system/5gpn-healthcheck.timer <<'EOF'
[Unit]
Description=Run 5GPN healthcheck every 5 minutes

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
Persistent=true

[Install]
WantedBy=timers.target
EOF
  systemctl daemon-reload
  systemctl enable --now 5gpn-healthcheck.timer
}

regenerate_ios_profile() {
  mkdir -p "${WWW_DIR}"
  local domain server_ip profile_url uuid1 uuid2
  domain=$(cat "${DNSDIST_DIR}/.domain" 2>/dev/null || echo "${DOMAIN:-}")
  server_ip=$(cat "${DNSDIST_DIR}/.public_ip" 2>/dev/null || public_ip)
  [[ -z "$domain" ]] && { warn "No domain found; skipping iOS profile regeneration."; return 0; }
  uuid1=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen)
  uuid2=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen)
  profile_url="http://${domain}:${IOS_PROFILE_PORT}/ios-dot.mobileconfig"

  cat > "${WWW_DIR}/probe" <<EOF
ok
EOF
  cat > "${WWW_DIR}/ios-dot.mobileconfig" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>PayloadContent</key>
  <array>
    <dict>
      <key>DNSSettings</key>
      <dict>
        <key>DNSProtocol</key><string>TLS</string>
        <key>ServerName</key><string>${domain}</string>
        <key>ServerAddresses</key><array><string>${server_ip}</string></array>
      </dict>
      <key>OnDemandRules</key>
      <array>
        <dict><key>InterfaceTypeMatch</key><string>WiFi</string><key>Action</key><string>Disconnect</string></dict>
        <dict><key>InterfaceTypeMatch</key><string>Cellular</string><key>Action</key><string>Connect</string><key>URLStringProbe</key><string>http://${server_ip}:${IOS_PROFILE_PORT}/probe</string></dict>
        <dict><key>Action</key><string>Disconnect</string></dict>
      </array>
      <key>PayloadDescription</key><string>Use ${domain} DNS over TLS on cellular 5GPN path only.</string>
      <key>PayloadDisplayName</key><string>5GPN Cellular DoT</string>
      <key>PayloadIdentifier</key><string>com.5gpn.${domain}.dnssettings</string>
      <key>PayloadType</key><string>com.apple.dnsSettings.managed</string>
      <key>PayloadUUID</key><string>${uuid1}</string>
      <key>PayloadVersion</key><integer>1</integer>
    </dict>
  </array>
  <key>PayloadDescription</key><string>5GPN DoT profile with OnDemand cellular probe.</string>
  <key>PayloadDisplayName</key><string>5GPN Cellular DoT</string>
  <key>PayloadIdentifier</key><string>com.5gpn.${domain}</string>
  <key>PayloadOrganization</key><string>5GPN</string>
  <key>PayloadRemovalDisallowed</key><false/>
  <key>PayloadType</key><string>Configuration</string>
  <key>PayloadUUID</key><string>${uuid2}</string>
  <key>PayloadVersion</key><integer>1</integer>
</dict>
</plist>
EOF

  cat > "${WWW_DIR}/index.html" <<EOF
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>5GPN iOS DoT</title></head>
<body><h1>5GPN iOS DoT</h1><p><a href="/ios-dot.mobileconfig">Install iOS profile</a></p></body></html>
EOF

  cat > /etc/systemd/system/proxy-gateway-ios-profile.service <<EOF
[Unit]
Description=5GPN iOS profile static server
After=network.target

[Service]
Type=simple
WorkingDirectory=${WWW_DIR}
ExecStart=/usr/bin/python3 -m http.server ${IOS_PROFILE_PORT} --bind 0.0.0.0
Restart=on-failure
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now proxy-gateway-ios-profile.service
  echo "$profile_url" > "${WWW_DIR}/ios-profile-url.txt"
  if command -v qrencode >/dev/null 2>&1; then
    qrencode -t ANSIUTF8 "$profile_url" | tee "${WWW_DIR}/ios-dot.qr.txt"
  else
    warn "qrencode not found. iOS profile URL: ${profile_url}"
  fi
  ok "iOS profile ready: ${profile_url}"
}

main() {
  need_root
  install_upstream_if_needed
  ensure_swap
  write_local_lists
  write_dnsdist_template
  write_update_script
  configure_firewall_and_services
  configure_rule_timer
  regenerate_ios_profile
  log "Generating and loading optimized rules."
  /usr/local/bin/update-dnsdist-rules.sh
  write_healthcheck
  /usr/local/bin/5gpn-healthcheck.sh

  echo ""
  ok "5GPN optimized installation completed."
  echo "Manage lists:"
  echo "  ${DNSDIST_DIR}/direct-local.txt"
  echo "  ${DNSDIST_DIR}/proxy-local.txt"
  echo "  ${DNSDIST_DIR}/block-local.txt"
  echo "Update rules now:"
  echo "  /usr/local/bin/update-dnsdist-rules.sh"
  echo "Healthcheck:"
  echo "  /usr/local/bin/5gpn-healthcheck.sh"
  if [[ -f "${WWW_DIR}/ios-dot.qr.txt" ]]; then
    echo "iOS QR:"
    cat "${WWW_DIR}/ios-dot.qr.txt"
  fi
}

main "$@"
